language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.6
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.6
    - gcc-5
    - g++-5

before_script:
  # UPDATE GCC TO GCC-5
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  
  # UPDATE CLANG TO CLANG-3.6
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
  
  # DISPLAY COMPILER VERSION
  - $CXX --version
  
  # UPDATE CMAKE TO >= 2.8.12
  - sudo add-apt-repository ppa:smspillaz/cmake-2.8.12 -y
  - sudo apt-get update -qq
  - sudo apt-get purge cmake -qq
  - sudo apt-get install cmake -qq
  - cmake --version
  
  # DOWNLOAD & INSTALL GLM LIBRARY
  - DEPENDENCY_GLM_BRANCH="0.9.5"
  - git clone -b $DEPENDENCY_GLM_BRANCH https://github.com/g-truc/glm.git glm
  - cd glm
  - cmake .
  - sudo make install
  - cd ..
  
  # DOWNLOAD & INSTALL GLEW LIBRARY
  - DEPENDENCY_GLEW_VERSION="1.13.0"
  - wget -O glew-${DEPENDENCY_GLEW_VERSION}.zip https://sourceforge.net/projects/glew/files/glew/${DEPENDENCY_GLEW_VERSION}/glew-${DEPENDENCY_GLEW_VERSION}.zip/download
  - unzip glew-${DEPENDENCY_GLEW_VERSION}.zip
  - cd glew-${DEPENDENCY_GLEW_VERSION}
  - make
  - sudo make install
  - cd ..
  
  # DOWNLOAD & INSTALL GLFW3 LIBRARY
  - git clone https://github.com/glfw/glfw.git glfw
  - cd glfw
  - cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make install
  - cd ..
  
  # DOWNLOAD & INSTALL FREETYPE2 LIBRARY
  - DEPENDENCY_FT2_VERSION="2.6"
  - DEPENDENCY_FT2_VERSION_FILE="26"
  - wget -O ft${DEPENDENCY_FT2_VERSION_FILE}.zip http://sourceforge.net/projects/freetype/files/freetype2/${DEPENDENCY_FT2_VERSION}/ft${DEPENDENCY_FT2_VERSION_FILE}.zip/download
  - unzip ft${DEPENDENCY_FT2_VERSION_FILE}.zip
  - cd freetype-${DEPENDENCY_FT2_VERSION}
  - cmake .
  - sudo make install
  - cd ..

script:
  - cmake .
  - make
